version: "3.8"
services:
  api:
    # image: thomas-oliver/nestjs-dockerized 
    build:
      dockerfile: Dockerfile
      context: .
      # Only will build development stage from our dockerfile
      target: development
    # Mount our host Directory to the docker container
    # Mount (.) current directory to the docker container thomas/src/app
    # reflect file changes from host to container
    volumes:
      - .:/thomas/src/app
      - ./thomas/src/app/node_modules
    # Run in Debug Mode: npm run start:debug --> Don't forget to start your vscode debugger!
    # Run in dev Mode: npm run start:dev
    command: npm run start:debug
    depends_on: 
      - postgres
    environment: 
      DATABASE_URL: postgres://user:password@postgres:5432/db
      NODE_ENV: development
      JWT_SECRET: 1hard_to_guess_secret7890a
      PORT: 3000
    ports:
      - 8080:3000
      # debugging port
      - 9229:9229

  postgres:
    image: postgres:10.4
    environment: 
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - 35000:5432

    ### Postgres Adminer ###
  postgres_admin:
    image: dpage/pgadmin4:4.28
    depends_on:
      - postgres
    environment: 
      PGADMIN_DEFAULT_EMAIL: admin@admin.de
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - 5050:80
